import 'dart:io';

import 'package:path/path.dart' as p;

import 'model/test_package.dart';

/// Writes one entrypoint that imports a package's test files and calls their
/// `main()`s.
///
/// **What it buys:** one compilation and one VM start-up instead of one per
/// file. Across seventy packages with a few hundred test files that is the
/// difference between a suite measured in minutes and one measured in tens of
/// minutes.
///
/// **What it costs, and why it is a flag rather than the default:** a
/// library-level `@Tags` or `@TestOn` annotation belongs to the file that
/// carries it, and a bundle is a different file. Tag filtering therefore
/// applies to the bundle as a whole. Any run that filters by tag — the `pr`
/// preset excludes `golden` and `integration` — has to run unbundled, so the
/// flag exists for the full runs where nothing is excluded.
final class TestBundle {
  /// Creates a bundle description.
  const TestBundle({required this.file, required this.fileCount});

  /// The generated entrypoint, inside the package's `test/` directory.
  ///
  /// It has to live there: the files it imports use relative paths and reach
  /// `test/support/…` helpers, and an entrypoint written to a temporary
  /// directory could not see them.
  final File file;

  /// How many test files it pulls in.
  final int fileCount;

  /// The name the generated file always has.
  ///
  /// It ends in `_test.dart` so that a stray copy is still picked up by a
  /// normal run rather than silently ignored, and it starts with an underscore
  /// so it sorts away from the real suites.
  static const String fileName = '_bundle_test.dart';

  /// Writes a bundle for [package], or `null` when it has fewer than two test
  /// files — bundling one file saves nothing and adds a file to explain.
  static TestBundle? write(TestPackage package) {
    final testDirectory = Directory(p.join(package.absolutePath, 'test'));
    if (!testDirectory.existsSync()) return null;

    final files =
        testDirectory
            .listSync(recursive: true, followLinks: false)
            .whereType<File>()
            .map((file) => p.relative(file.path, from: testDirectory.path))
            .where((relative) => relative.endsWith('_test.dart'))
            .where((relative) => p.basename(relative) != fileName)
            .map((relative) => p.posix.joinAll(p.split(relative)))
            .toList()
          ..sort();

    if (files.length < 2) return null;

    final imports = <String>[];
    final calls = <String>[];
    for (final (index, relative) in files.indexed) {
      imports.add("import '$relative' as suite$index;");
      // A group per file, so a failure names the file it came from. Without
      // it, every test in the bundle reports as belonging to one entrypoint
      // and the first job of anybody reading CI is to go and find out where.
      calls.add("  group('$relative', suite$index.main);");
    }

    final source = [
      '// GENERATED by tooling/test_runner --bundle. Do not commit.',
      '//',
      '// One entrypoint for this package, so the suite compiles and starts',
      '// once instead of once per file. Deleted when the run finishes.',
      "import 'package:test/test.dart';",
      '',
      ...imports,
      '',
      'void main() {',
      ...calls,
      '}',
      '',
    ].join('\n');

    final file = File(p.join(testDirectory.path, fileName))
      ..writeAsStringSync(source);
    return TestBundle(file: file, fileCount: files.length);
  }

  /// Removes the generated entrypoint.
  ///
  /// Called from a `finally`, because a bundle left behind by a crashed run
  /// would be committed by the next person who typed `git add -A`.
  void delete() {
    if (file.existsSync()) file.deleteSync();
  }
}
