import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

/// This app's container.
///
/// A `GetIt` instance rather than *the* `GetIt` instance. `GetIt.instance` is
/// a global, and a global container is a container two tests share: the first
/// test's `FakeHttpTransport` still holds the second test's queued responses,
/// and the failure looks like a bug in an adapter.
///
/// It is also the only `GetIt` in the workspace. Rule I5 keeps service
/// locators out of every package, so nothing below `apps/` can reach this even
/// if somebody imported it — a package that tried would fail `arch_check`
/// before it failed review.
final GetIt harnessContainer = GetIt.asNewInstance();

/// Registers everything this app composes.
///
/// Generated by `injectable_generator`, which is the one generator §4.1 puts
/// in `apps/*` only. The list it produces is this app's composition, and the
/// reason it can be generated at all is that every module in `di/` is written
/// by hand: rule I6 forbids an annotation inside a package, so there is
/// nothing to scan out there and everything to read in here.
@InjectableInit()
GetIt configureHarness() => harnessContainer.init();
