/// The push contract, its Firebase-backed adapter, and the DTO that turns a
/// provider payload into something the product can act on.
///
/// This is the package where the code-generation rules become concrete.
/// `PushMessageDto` is generated by `json_serializable`, which §10.1 allows in
/// exactly two places — `_infrastructure` and `platform/*` — and the reason is
/// visible in the DTO's own fields: their names and their optionality are
/// shaped by what a push provider sends, not by what the product means. The
/// same class in an `_api` package is rule G2's violation, and `build.yaml`
/// here is the file `arch_check` reads to prove it did not happen.
///
/// The mapper next to it is hand-written, which is the other half of the same
/// convention. Decoding is generated; deciding what an unrecognised message
/// kind *means* is a product judgement, and it stays where it can be read.
///
/// The judgement that matters: nothing arriving on this stream is ever an
/// error. A payload this version cannot parse becomes a message of an unknown
/// kind carrying its raw data, because a fleet updates over weeks and a server
/// sending a shape the app has not seen is normal traffic. An adapter that
/// threw there would take down a stream handler for a message it could simply
/// have ignored.
library;

export 'src/fake_push_messaging_client.dart';
export 'src/firebase_push_messaging_client.dart';
export 'src/push_failure.dart';
export 'src/push_message.dart';
export 'src/push_message_dto.dart';
export 'src/push_message_kind.dart';
export 'src/push_message_mapper.dart';
export 'src/push_messaging_client.dart';
