import '../model/dependency_graph.dart';
import '../model/package_node.dart';
import 'dot.dart';
import 'mermaid.dart';
import 'palette.dart';

/// Assembles `docs/dependency-graph.md`.
///
/// **Nothing here is time-stamped.** The file is generated and committed, so a
/// run that changed one byte per invocation would fail the staleness gate on
/// every commit and teach everybody to ignore it.
abstract final class GraphDocument {
  /// The whole document, for [graph].
  static String render(DependencyGraph graph) {
    final cycles = graph.cycles();
    final counts = <String, int>{};
    for (final node in graph.nodes) {
      final key = node.typeId ?? 'untyped';
      counts[key] = (counts[key] ?? 0) + 1;
    }

    return [
      _header,
      _summary(graph, counts, cycles),
      _cycles(cycles),
      _legend(counts),
      _constitution(graph),
      _mutualApi(graph),
      _feature(graph),
      _inventory(graph),
      _dot(graph),
    ].join('\n');
  }

  static const String _header = '''
# Dependency graph

<!-- Generated by tooling/dep_graph. Do not hand-edit. -->

```bash
dart run tooling/dep_graph/bin/dep_graph.dart          # rewrite this file
dart run tooling/dep_graph/bin/dep_graph.dart --check  # fail if it is stale
```

Edges are workspace packages only. A third-party dependency is a fact about a
package rather than about the shape of the repository, and drawing seventy of
them would bury the dozen that carry the argument. Dashed edges come from
`dev_dependencies:`, which is how a `_testing` package reaches its consumers
without shipping in anybody's product build.
''';

  static String _summary(
    DependencyGraph graph,
    Map<String, int> counts,
    List<List<String>> cycles,
  ) {
    final runtime = graph.runtimeEdges.length;
    final dev = graph.edges.length - runtime;
    return '''
## Summary

| | |
|---|---|
| Packages | ${graph.nodes.length} |
| Runtime edges | $runtime |
| Dev-dependency edges | $dev |
| Cycles | ${cycles.isEmpty ? 'none' : cycles.length} |
''';
  }

  static String _cycles(List<List<String>> cycles) {
    if (cycles.isEmpty) {
      return '''
## Cycles

None. This is success criterion 4 of the specification, and the reason it holds
is the rule in §2 of the dependency rules: when two features need each other,
the answer is mutual `_api` dependencies rather than a `shared` package. A
contract package depends on no implementation, so the edges cannot close a
loop — see the payments/shipments diagram below.
''';
    }
    return [
      '## Cycles',
      '',
      '**${cycles.length} found.** Each one is a set of packages that can only',
      'be built together, which means none of them can be reasoned about',
      'alone.',
      '',
      for (final cycle in cycles) '- ${cycle.join(' → ')} → ${cycle.first}',
      '',
    ].join('\n');
  }

  static String _legend(Map<String, int> counts) => [
    '## Legend',
    '',
    '| Colour | Type | Packages |',
    '|---|---|---|',
    for (final typeId in counts.keys.toList()..sort())
      _legendRow(typeId, counts[typeId]!),
    '',
  ].join('\n');

  static String _legendRow(String typeId, int count) {
    final style = styleFor(typeId);
    return '| `${style.fill}` | ${style.label} | $count |';
  }

  static String _constitution(DependencyGraph graph) =>
      '''
## The constitution, as it was actually built

One node per package *type*, one edge wherever a package of one type depends on
a package of another. Compare it against the table in §2 of
[`DEPENDENCY_RULES.md`](DEPENDENCY_RULES.md): an edge here that is not in that
table would be a violation `arch_check` fails on, and an edge in the table that
is missing here is a permission nothing has needed yet.

```mermaid
${Mermaid.typeGraph(graph)}
```
''';

  static String _mutualApi(DependencyGraph graph) {
    final names = {
      for (final node in graph.nodes)
        if (node.owningFeature == 'payments' ||
            node.owningFeature == 'shipments')
          node.name,
    };
    return '''
## Scenario 1: two features that need each other, and no cycle

`payments` needs a shipment to attach a collection to; `shipments` needs to
show whether a parcel has been paid for. Neither `_application` package appears
in the other's pubspec — each depends on the other's **contract** only. A
contract package depends on no implementation, so the two arrows cannot close
a loop, and the answer to a mutual need is never a `shared` package.

```mermaid
${Mermaid.subgraph(graph, names)}
```
''';
  }

  static String _feature(DependencyGraph graph) =>
      '''
## One feature in full split, and everything it touches

`routing`, with its five packages and every workspace package they reach.
`routing_application` sees the contract and never an adapter;
`routing_infrastructure` sees the contract and the technology packages;
neither sees the other. The only place they meet is an app.

```mermaid
${Mermaid.feature(graph, 'routing')}
```
''';

  static String _inventory(DependencyGraph graph) => [
    '## Every package',
    '',
    '| Package | Type | Depends on (workspace) |',
    '|---|---|---|',
    for (final node in graph.nodes) _inventoryRow(graph, node),
    '',
  ].join('\n');

  static String _inventoryRow(DependencyGraph graph, PackageNode node) {
    final type = node.typeId ?? '**untyped**';
    final deps = _internal(graph, node.dependencies);
    return '| `${node.name}` | $type | $deps |';
  }

  static String _internal(DependencyGraph graph, List<String> names) {
    final internal = [
      for (final name in names)
        if (graph.byName(name) != null) '`$name`',
    ];
    return internal.isEmpty ? '—' : internal.join(', ');
  }

  static String _dot(DependencyGraph graph) =>
      '''
## The complete graph, as Graphviz DOT

Mermaid is given three views and DOT is given everything, and the reason is
layout: `dot` ranks a directed acyclic graph so that every edge points the same
way, which turns seventy-odd packages into a picture of the rings. Render it
with `dot -Tsvg`.

```dot
${Dot.render(graph)}
```
''';
}
